export const TECH_STACK_OPTIONS = [
  "react",
  "next.js",
  "vue",
  "svelte",
  "angular",
  "tailwind",
  "css-modules",
  "styled-components",
  "typescript",
  "javascript",
  "python",
  "node.js",
  "convex",
  "supabase",
  "firebase",
  "prisma",
  "drizzle",
  "mongodb",
  "postgresql",
  "clerk",
  "stripe",
  "three.js",
  "framer-motion",
  "gsap",
] as const;

export const DESIGN_STYLE_OPTIONS = [
  "minimal",
  "japandi",
  "neobrutalism",
  "glassmorphism",
  "dark-mode",
  "light-mode",
  "retro",
  "swiss",
  "kinetic",
  "modernist",
  "skeuomorphic",
  "flat",
  "material",
  "neumorphism",
  "cyberpunk",
  "editorial",
  "organic",
  "geometric",
  "monochrome",
  "colorful",
  "gradient-heavy",
] as const;

export const CATEGORY_OPTIONS = [
  { value: "landing-page", label: "Landing Page" },
  { value: "dashboard", label: "Dashboard" },
  { value: "portfolio", label: "Portfolio" },
  { value: "e-commerce", label: "E-commerce" },
  { value: "saas", label: "SaaS" },
  { value: "blog", label: "Blog" },
  { value: "documentation", label: "Documentation" },
  { value: "tool", label: "Tool" },
  { value: "game", label: "Game" },
  { value: "social", label: "Social" },
  { value: "ai-app", label: "AI App" },
  { value: "admin-panel", label: "Admin Panel" },
  { value: "other", label: "Other" },
] as const;
