/**
 * Serialise environment variables into `.env` file format.
 *
 * ## Why this is not `${key}=${value}`
 *
 * A value is arbitrary user or provider data. Interpolating it raw lets the value
 * escape its own line:
 *
 *     SUPABASE_URL=https://x.supabase.co
 *     ADMIN_TOKEN=totally-legit
 *
 * ...is what you get from a single variable whose value contains a newline. Every
 * dotenv parser reads that as two variables, so an attacker who controls one value
 * controls every variable after it. Keys are already validated against
 * `[A-Za-z_][A-Za-z0-9_]*`, but values cannot be constrained that way — a
 * connection string legitimately contains `:`, `/`, `@`, `?` and `&`.
 *
 * So every value is double-quoted with `\`, `"`, newline, carriage return and tab
 * escaped. That is the form `dotenv`, Vite, Next.js and docker-compose all agree
 * on.
 *
 * ## Why not just refuse newlines
 *
 * Because they are legitimate. A private key or a PEM certificate is multi-line and
 * is a perfectly normal thing to put in an environment variable. Rejecting them
 * would break a real use case; escaping them breaks nothing.
 */

import { assertValidEnvKey } from "./env-keys";

export interface EnvEntry {
  key: string;
  value: string;
}

/**
 * Escape a value for a double-quoted `.env` assignment.
 *
 * Backslash is escaped first — doing it later would double-escape the backslashes
 * introduced by the other replacements.
 */
export function escapeDotenvValue(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r/g, "\\r")
    .replace(/\n/g, "\\n")
    .replace(/\t/g, "\\t");
}

/**
 * Render entries as the contents of a `.env` file.
 *
 * Keys are validated rather than escaped: an invalid key has no safe encoding, and
 * silently mangling it would produce a variable the app cannot read under a name
 * the user did not choose.
 *
 * Sorted for deterministic output, so an unchanged set of variables produces a
 * byte-identical file and does not needlessly invalidate caches or show up as a
 * spurious change.
 */
export function serialiseDotenv(entries: readonly EnvEntry[]): string {
  const seen = new Set<string>();
  const lines: string[] = [
    "# Generated by Codenaya from this project's integrations.",
    "# Edit these in the Integrations panel — changes here are overwritten.",
    "",
  ];

  const sorted = [...entries].sort((a, b) => (a.key < b.key ? -1 : 1));

  for (const entry of sorted) {
    assertValidEnvKey(entry.key);

    // Last write wins, matching how dotenv itself resolves duplicates, but the
    // duplicate is dropped rather than emitted twice so the file stays honest
    // about what is in effect.
    if (seen.has(entry.key)) continue;
    seen.add(entry.key);

    lines.push(`${entry.key}="${escapeDotenvValue(entry.value)}"`);
  }

  return `${lines.join("\n")}\n`;
}

/**
 * Build the `envs` map passed to a process.
 *
 * Process environments take raw values — escaping is only needed when the value
 * has to survive a file format. Escaping here would put literal `\n` into the
 * running app.
 */
export function toProcessEnv(
  entries: readonly EnvEntry[],
): Record<string, string> {
  const env: Record<string, string> = {};
  for (const entry of entries) {
    assertValidEnvKey(entry.key);
    env[entry.key] = entry.value;
  }
  return env;
}
