import { describe, expect, it } from "vitest";

import { escapeDotenvValue, serialiseDotenv, toProcessEnv } from "./dotenv";

/**
 * The injection case is the reason this module exists. A value containing a newline
 * would otherwise become a second variable assignment, so whoever controls one
 * value controls every variable after it.
 */

describe("escapeDotenvValue", () => {
  it("escapes newlines so a value cannot become a new assignment", () => {
    expect(escapeDotenvValue("a\nb")).toBe("a\\nb");
    expect(escapeDotenvValue("a\r\nb")).toBe("a\\r\\nb");
  });

  it("escapes double quotes so a value cannot close its own quoting", () => {
    expect(escapeDotenvValue('say "hi"')).toBe('say \\"hi\\"');
  });

  it("escapes backslashes before anything else", () => {
    // If backslash were escaped last it would double-escape the backslashes the
    // other replacements introduce, corrupting the value.
    expect(escapeDotenvValue("a\\b")).toBe("a\\\\b");
    expect(escapeDotenvValue('a\\"b')).toBe('a\\\\\\"b');
  });

  it("escapes tabs", () => {
    expect(escapeDotenvValue("a\tb")).toBe("a\\tb");
  });

  it("leaves ordinary connection-string punctuation alone", () => {
    // These are legitimate and must survive untouched, or the app gets a broken DSN.
    const dsn = "postgresql://user:pw@host:5432/db?sslmode=require&x=1";
    expect(escapeDotenvValue(dsn)).toBe(dsn);
  });

  it("leaves an empty value alone", () => {
    expect(escapeDotenvValue("")).toBe("");
  });
});

describe("serialiseDotenv", () => {
  it("quotes every value", () => {
    const output = serialiseDotenv([
      { key: "NEXT_PUBLIC_URL", value: "https://x.supabase.co" },
    ]);

    expect(output).toContain('NEXT_PUBLIC_URL="https://x.supabase.co"');
  });

  it("neutralises an injection attempt", () => {
    const output = serialiseDotenv([
      { key: "SAFE", value: "value\nADMIN_TOKEN=injected" },
    ]);

    // The forged assignment must not exist as its own line.
    const lines = output.split("\n").filter((l) => l && !l.startsWith("#"));
    expect(lines).toHaveLength(1);
    expect(output).not.toMatch(/^ADMIN_TOKEN=/m);
    expect(output).toContain('SAFE="value\\nADMIN_TOKEN=injected"');
  });

  it("handles a multi-line PEM value", () => {
    // Legitimately multi-line, so it must be escaped rather than rejected.
    const key = "-----BEGIN PRIVATE KEY-----\nabc\ndef\n-----END PRIVATE KEY-----";
    const output = serialiseDotenv([{ key: "GOOGLE_PRIVATE_KEY", value: key }]);

    const lines = output.split("\n").filter((l) => l && !l.startsWith("#"));
    expect(lines).toHaveLength(1);
    expect(output).toContain("\\n");
  });

  it("rejects an invalid key rather than mangling it", () => {
    // A mangled key produces a variable the app cannot read under a name the user
    // did not choose — worse than a clear failure.
    expect(() =>
      serialiseDotenv([{ key: "BAD KEY", value: "x" }]),
    ).toThrow(/not a valid environment/);

    expect(() =>
      serialiseDotenv([{ key: "EVIL\nINJECTED", value: "x" }]),
    ).toThrow(/not a valid environment/);
  });

  it("is deterministic and sorted", () => {
    const a = serialiseDotenv([
      { key: "B", value: "2" },
      { key: "A", value: "1" },
    ]);
    const b = serialiseDotenv([
      { key: "A", value: "1" },
      { key: "B", value: "2" },
    ]);

    expect(a).toBe(b);
    expect(a.indexOf('A="1"')).toBeLessThan(a.indexOf('B="2"'));
  });

  it("drops duplicate keys instead of emitting both", () => {
    const output = serialiseDotenv([
      { key: "K", value: "first" },
      { key: "K", value: "second" },
    ]);

    const assignments = output.split("\n").filter((l) => l.startsWith("K="));
    expect(assignments).toHaveLength(1);
  });

  it("includes a header explaining the file is generated", () => {
    const output = serialiseDotenv([{ key: "A", value: "1" }]);
    expect(output).toMatch(/^# Generated by Codenaya/);
    expect(output).toMatch(/overwritten/);
  });

  it("ends with a trailing newline", () => {
    expect(serialiseDotenv([{ key: "A", value: "1" }]).endsWith("\n")).toBe(true);
  });

  it("produces a valid file for no entries", () => {
    const output = serialiseDotenv([]);
    expect(output).toMatch(/^# Generated/);
    expect(output.split("\n").filter((l) => l && !l.startsWith("#"))).toEqual([]);
  });
});

describe("toProcessEnv", () => {
  it("passes values through raw, without dotenv escaping", () => {
    // A process environment takes real values. Escaping here would put a literal
    // backslash-n into the running application.
    const env = toProcessEnv([{ key: "PEM", value: "a\nb" }]);
    expect(env.PEM).toBe("a\nb");
  });

  it("validates keys", () => {
    expect(() => toProcessEnv([{ key: "BAD KEY", value: "x" }])).toThrow(
      /not a valid environment/,
    );
  });

  it("lets a later entry win", () => {
    expect(toProcessEnv([
      { key: "K", value: "first" },
      { key: "K", value: "second" },
    ]).K).toBe("second");
  });

  it("returns an empty object for no entries", () => {
    expect(toProcessEnv([])).toEqual({});
  });
});
